// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zcrypta.Models;

public partial class TradingPair
{
    public long Id { get; set; }

    public string Base { get; set; }

    public string Quote { get; set; }

    public virtual ICollection<UserSignalStrategy> UserSignalStrategies { get; set; } = new List<UserSignalStrategy>();
}