// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zcrypta.Models;

public partial class TradingSignal
{
    public long Id { get; set; }

    public long StrategyId { get; set; }

    public string Symbol { get; set; }

    public int SignalType { get; set; }

    public DateTime? DateTime { get; set; }

    public int StrategyType { get; set; }

    public int Interval { get; set; }

    public virtual ICollection<UserTradingSignal> UserTradingSignals { get; set; } = new List<UserTradingSignal>();
}