// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zcrypta.Models;

public partial class UserSignalStrategy
{
    public long Id { get; set; }

    public string UserId { get; set; }

    public long StrategyId { get; set; }

    public long TradingPairId { get; set; }

    public virtual SignalStrategy Strategy { get; set; }

    public virtual TradingPair TradingPair { get; set; }
}